name: build

on:
  push:
    branches: [ 'main' ]
  pull_request:

# one running workflow per branch, others will wait
concurrency: ${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.0
